# Generated by Django 4.2.1 on 2023-06-23 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0003_rating_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "no_of_guests",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.BooleanField(db_index=True, default=0),
        ),
    ]
